var testData = {"pageData": {
    "exceptionType": "null",
    "aut": "null",
    "timerStart": "0",
    "elementUsageMap": {},
    "failedStep": "null",
    "elementUsage": [],
    "iterationCount": "0",
    "csvOutput": "",
    "testStatus": "PASSED",
    "dataMap": {"LoginCredentials": {
        "recordMap": {
            "UserName": "admin",
            "Password": "demo123"
        },
        "recordName": "TestUser_One",
        "typeName": "LoginCredentials",
        "active": true,
        "containsChildren": false
    }},
    "pageMap": {
        "CloudSchool.CSHomePage": {
            "m0": "public native int java.lang.Object.hashCode()",
            "m1": "public boolean java.lang.Object.equals(java.lang.Object)",
            "m2": "public java.lang.String java.lang.Object.toString()",
            "m3": "public abstract java.lang.String org.xframium.page.keyWord.KeyWordPage.getPageName()",
            "m4": "public abstract void org.xframium.page.keyWord.KeyWordPage.setPageName(java.lang.String)",
            "m5": "public abstract void org.xframium.page.Page.setExecutionContext(org.xframium.reporting.ExecutionContextTest)",
            "m6": "public abstract org.xframium.reporting.ExecutionContextTest org.xframium.page.Page.getExecutionContext()",
            "m7": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String)",
            "m8": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String,java.lang.String)",
            "m9": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(org.xframium.page.ElementDescriptor)",
            "m11": "public abstract void org.xframium.page.Page.setDriver(java.lang.Object)",
            "m10": "public abstract void org.xframium.page.Page.initializePage()"
        },
        "CloudSchool.CSLoginPage": {
            "m0": "public native int java.lang.Object.hashCode()",
            "m1": "public boolean java.lang.Object.equals(java.lang.Object)",
            "m2": "public java.lang.String java.lang.Object.toString()",
            "m3": "public abstract java.lang.String org.xframium.page.keyWord.KeyWordPage.getPageName()",
            "m4": "public abstract void org.xframium.page.keyWord.KeyWordPage.setPageName(java.lang.String)",
            "m5": "public abstract void org.xframium.page.Page.setExecutionContext(org.xframium.reporting.ExecutionContextTest)",
            "m6": "public abstract org.xframium.reporting.ExecutionContextTest org.xframium.page.Page.getExecutionContext()",
            "m7": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String)",
            "m8": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String,java.lang.String)",
            "m9": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(org.xframium.page.ElementDescriptor)",
            "m11": "public abstract void org.xframium.page.Page.setDriver(java.lang.Object)",
            "m10": "public abstract void org.xframium.page.Page.initializePage()"
        }
    },
    "pageUsageMap": {},
    "timerName": "null",
    "inStepListener": false,
    "startTime": {
        "dateTime": "11/22/2019-20:50:56",
        "dateOnly": "11/22/2019",
        "timeOnly": "20:50:56",
        "raw": 1574455856720
    },
    "xFID": "98dbe9a2-fa57-404d-8cf6-5dae6dec1f7e",
    "testName": "TC01_ValidLogin",
    "dC": {
        "mobileEmulationEnabled": false,
        "timeouts": {
            "implicit": "0",
            "pageLoad": "300000",
            "script": "30000"
        },
        "hasTouchScreen": false,
        "platform": "XP",
        "acceptSslCerts": false,
        "goog:chromeOptions": {"debuggerAddress": "localhost:56000"},
        "acceptInsecureCerts": false,
        "webStorageEnabled": true,
        "browserName": "chrome",
        "takesScreenshot": true,
        "javascriptEnabled": true,
        "platformName": "XP",
        "setWindowRect": true,
        "unexpectedAlertBehaviour": "ignore",
        "applicationCacheEnabled": false,
        "rotatable": false,
        "networkConnectionEnabled": false,
        "chrome": {
            "chromedriverVersion": "78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877})",
            "userDataDir": "C:\\Users\\abbey\\AppData\\Local\\Temp\\scoped_dir8188_1963813581"
        },
        "takesHeapSnapshot": true,
        "pageLoadStrategy": "normal",
        "unhandledPromptBehavior": "ignore",
        "strictFileInteractability": false,
        "databaseEnabled": false,
        "handlesAlerts": true,
        "version": "78.0.3904.97",
        "browserConnectionEnabled": false,
        "proxy": "Proxy()",
        "nativeEvents": true,
        "webdriver.remote.sessionid": "03acad6f-ddba-439d-9027-7ebe3ef488ed",
        "locationContextEnabled": true,
        "cssSelectorsEnabled": true
    },
    "executionParameters": {
        "ALL_IN_ONE": "enabled",
        "ALL_IN_ONE_PATH": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\11-22_20-51-03-142\\Windows chrome\\TC01_ValidLogin\\allInOne.html",
        "ALL_IN_ONE_ABS": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\11-22_20-51-03-142\\Windows chrome\\TC01_ValidLogin\\allInOne.html",
        "ALL_IN_ONE_FILE": "allInOne.html",
        "CONSOLE_LOG": "enabled",
        "CONSOLE_LOG_ABS": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\11-22_20-51-03-142\\Windows chrome\\TC01_ValidLogin\\console.txt",
        "CONSOLE_LOG_FILE": "console.txt",
        "CONSOLE_LOG_PATH": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\11-22_20-51-03-142\\Windows chrome\\TC01_ValidLogin\\console.txt"
    },
    "c": {
        "browserName": "chrome",
        "model": "Chrome",
        "_testName": "TC01_ValidLogin",
        "platformName": "Windows",
        "version": "",
        "platform": "ANY"
    },
    "test": {
        "deviceTags": "null",
        "outputPage": "null",
        "severity": "0",
        "timed": false,
        "reliesOn": "null",
        "os": "null",
        "contentKeys": [""],
        "log": "org.apache.commons.logging.impl.Jdk14Logger@6ea34488",
        "inputPage": "null",
        "count": "0",
        "active": true,
        "description": "null",
        "threshold": "0",
        "expectedParameters": [],
        "stepList": [
            {
                "deviceTags": "null",
                "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
                "threshold": "0",
                "sFailure": "ERROR",
                "pageName": "null",
                "context": "null",
                "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                "waitFor": "null",
                "validation": "null",
                "reportingTokens": [],
                "image": "null",
                "timed": false,
                "active": true,
                "stepList": [],
                "version": "null",
                "DATA_PATTERN": "data\\{(\\w*)\\}",
                "name": "Login_Function",
                "parameterList": [],
                "device": "null",
                "successReport": "null",
                "failureReport": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                "siteName": "null",
                "description": "",
                "poi": "null",
                "tagNames": "null",
                "trace": false,
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "tokenList": [],
                "featureId": "11",
                "startAt": false,
                "kwName": "Call Test/Function",
                "numberGenerator": "java.util.Random@30ea2300",
                "inverse": false,
                "os": "null",
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
                "kw": "CALL2",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "allowMultiple": false,
                "dataTable": "null",
                "appContext": "null",
                "category": "Flow Control",
                "orMapping": false,
                "waitTime": "0"
            },
            {
                "deviceTags": "null",
                "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
                "threshold": "0",
                "sFailure": "ERROR",
                "pageName": "null",
                "context": "null",
                "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                "waitFor": "null",
                "validation": "null",
                "reportingTokens": [],
                "image": "null",
                "timed": false,
                "active": true,
                "stepList": [],
                "version": "null",
                "DATA_PATTERN": "data\\{(\\w*)\\}",
                "name": "Logout_Function",
                "parameterList": [],
                "device": "null",
                "successReport": "null",
                "failureReport": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                "siteName": "null",
                "description": "",
                "poi": "null",
                "tagNames": "null",
                "trace": false,
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "tokenList": [],
                "featureId": "11",
                "startAt": false,
                "kwName": "Call Test/Function",
                "numberGenerator": "java.util.Random@30ea2300",
                "inverse": false,
                "os": "null",
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
                "kw": "CALL2",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "allowMultiple": false,
                "dataTable": "null",
                "appContext": "null",
                "category": "Flow Control",
                "orMapping": false,
                "waitTime": "0"
            }
        ],
        "priority": "0",
        "testTags": [""],
        "mode": "null",
        "operationList": "null",
        "trace": "OFF",
        "linkId": "null",
        "dataDriver": "null",
        "name": "TC01_ValidLogin",
        "dataProviders": ["LoginCredentials.TestUser_One"]
    },
    "sPMap": {
        "__outputFolder": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output",
        "sun.desktop": "windows",
        "awt.toolkit": "sun.awt.windows.WToolkit",
        "file.encoding.pkg": "sun.io",
        "java.specification.version": "1.8",
        "sun.cpu.isalist": "amd64",
        "sun.jnu.encoding": "Cp1252",
        "java.class.path": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\xframium-driver\\bin;C:\\Users\\abbey\\.m2\\repository\\commons-logging\\commons-logging\\1.1.1\\commons-logging-1.1.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\testng\\testng\\6.9.10\\testng-6.9.10.jar;C:\\Users\\abbey\\.m2\\repository\\com\\beust\\jcommander\\1.48\\jcommander-1.48.jar;C:\\Users\\abbey\\.m2\\repository\\org\\beanshell\\bsh\\2.0b4\\bsh-2.0b4.jar;C:\\Users\\abbey\\.m2\\repository\\org\\xframium\\xframium-java\\1.0.21\\xframium-java-1.0.21.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\poi\\poi-ooxml\\3.11\\poi-ooxml-3.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\poi\\poi\\3.11\\poi-3.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\poi\\poi-ooxml-schemas\\3.11\\poi-ooxml-schemas-3.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\xmlbeans\\xmlbeans\\2.6.0\\xmlbeans-2.6.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-java\\3.13.0\\selenium-java-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-chrome-driver\\3.13.0\\selenium-chrome-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-edge-driver\\3.13.0\\selenium-edge-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-firefox-driver\\3.13.0\\selenium-firefox-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-ie-driver\\3.13.0\\selenium-ie-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-opera-driver\\3.13.0\\selenium-opera-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-remote-driver\\3.13.0\\selenium-remote-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-safari-driver\\3.13.0\\selenium-safari-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-support\\3.13.0\\selenium-support-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\net\\bytebuddy\\byte-buddy\\1.8.3\\byte-buddy-1.8.3.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\commons\\commons-exec\\1.3\\commons-exec-1.3.jar;C:\\Users\\abbey\\.m2\\repository\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\code\\gson\\gson\\2.8.4\\gson-2.8.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\guava\\guava\\25.0-jre\\guava-25.0-jre.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\code\\findbugs\\jsr305\\1.3.9\\jsr305-1.3.9.jar;C:\\Users\\abbey\\.m2\\repository\\org\\checkerframework\\checker-compat-qual\\2.0.0\\checker-compat-qual-2.0.0.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\errorprone\\error_prone_annotations\\2.1.3\\error_prone_annotations-2.1.3.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\j2objc\\j2objc-annotations\\1.1\\j2objc-annotations-1.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\codehaus\\mojo\\animal-sniffer-annotations\\1.14\\animal-sniffer-annotations-1.14.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\httpcomponents\\httpclient\\4.5.5\\httpclient-4.5.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\httpcomponents\\httpcore\\4.4.9\\httpcore-4.4.9.jar;C:\\Users\\abbey\\.m2\\repository\\com\\squareup\\okhttp3\\okhttp\\3.10.0\\okhttp-3.10.0.jar;C:\\Users\\abbey\\.m2\\repository\\com\\squareup\\okio\\okio\\1.14.1\\okio-1.14.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-api\\3.13.0\\selenium-api-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-server\\3.13.0\\selenium-server-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.7\\commons-lang3-3.7.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\commons\\commons-text\\1.1\\commons-text-1.1.jar;C:\\Users\\abbey\\.m2\\repository\\commons-io\\commons-io\\2.6\\commons-io-2.6.jar;C:\\Users\\abbey\\.m2\\repository\\commons-net\\commons-net\\3.6\\commons-net-3.6.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit\\2.30\\htmlunit-2.30.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit-core-js\\2.28\\htmlunit-core-js-2.28.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit-cssparser\\1.0.0\\htmlunit-cssparser-1.0.0.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\neko-htmlunit\\2.30\\neko-htmlunit-2.30.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\httpcomponents\\httpmime\\4.5.5\\httpmime-4.5.5.jar;C:\\Users\\abbey\\.m2\\repository\\net\\jcip\\jcip-annotations\\1.0\\jcip-annotations-1.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\jetty-repacked\\9.4.7.v20171121\\jetty-repacked-9.4.7.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-client\\9.4.7.v20170914\\jetty-client-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-http\\9.4.8.v20171121\\jetty-http-9.4.8.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-io\\9.4.8.v20171121\\jetty-io-9.4.8.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-util\\9.4.8.v20171121\\jetty-util-9.4.8.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-xml\\9.4.7.v20170914\\jetty-xml-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\htmlunit-driver\\2.30.0\\htmlunit-driver-2.30.0.jar;C:\\Users\\abbey\\.m2\\repository\\javax\\servlet\\javax.servlet-api\\3.1.0\\javax.servlet-api-3.1.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-api\\9.4.7.v20170914\\websocket-api-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-client\\9.4.7.v20170914\\websocket-client-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-common\\9.4.7.v20170914\\websocket-common-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\xalan\\serializer\\2.7.2\\serializer-2.7.2.jar;C:\\Users\\abbey\\.m2\\repository\\xalan\\xalan\\2.7.2\\xalan-2.7.2.jar;C:\\Users\\abbey\\.m2\\repository\\xerces\\xercesImpl\\2.11.0\\xercesImpl-2.11.0.jar;C:\\Users\\abbey\\.m2\\repository\\xml-apis\\xml-apis\\1.4.01\\xml-apis-1.4.01.jar;C:\\Users\\abbey\\.m2\\repository\\org\\yaml\\snakeyaml\\1.19\\snakeyaml-1.19.jar;C:\\Users\\abbey\\.m2\\repository\\org\\reflections\\reflections\\0.9.11\\reflections-0.9.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\javassist\\javassist\\3.21.0-GA\\javassist-3.21.0-GA.jar;C:\\Users\\abbey\\.m2\\repository\\io\\appium\\java-client\\6.1.0\\java-client-6.1.0.jar;C:\\Users\\abbey\\.m2\\repository\\cglib\\cglib\\3.2.6\\cglib-3.2.6.jar;C:\\Users\\abbey\\.m2\\repository\\org\\ow2\\asm\\asm\\6.0\\asm-6.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\ant\\ant\\1.9.6\\ant-1.9.6.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\ant\\ant-launcher\\1.9.6\\ant-launcher-1.9.6.jar;C:\\Users\\abbey\\.m2\\repository\\commons-validator\\commons-validator\\1.6\\commons-validator-1.6.jar;C:\\Users\\abbey\\.m2\\repository\\commons-beanutils\\commons-beanutils\\1.9.2\\commons-beanutils-1.9.2.jar;C:\\Users\\abbey\\.m2\\repository\\commons-digester\\commons-digester\\1.8.1\\commons-digester-1.8.1.jar;C:\\Users\\abbey\\.m2\\repository\\commons-collections\\commons-collections\\3.2.2\\commons-collections-3.2.2.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-context\\5.0.5.RELEASE\\spring-context-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-aop\\5.0.5.RELEASE\\spring-aop-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-beans\\5.0.5.RELEASE\\spring-beans-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-core\\5.0.5.RELEASE\\spring-core-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-jcl\\5.0.5.RELEASE\\spring-jcl-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-expression\\5.0.5.RELEASE\\spring-expression-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\aspectj\\aspectjweaver\\1.9.1\\aspectjweaver-1.9.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\openpnp\\opencv\\3.2.0-1\\opencv-3.2.0-1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-runtime\\2.2.11\\jaxb-runtime-2.2.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\jvnet\\staxex\\stax-ex\\1.7.7\\stax-ex-1.7.7.jar;C:\\Users\\abbey\\.m2\\repository\\com\\sun\\xml\\fastinfoset\\FastInfoset\\1.2.13\\FastInfoset-1.2.13.jar;C:\\Users\\abbey\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-core\\2.2.11\\jaxb-core-2.2.11.jar;C:\\Users\\abbey\\.m2\\repository\\javax\\xml\\bind\\jaxb-api\\2.2.12-b140109.1041\\jaxb-api-2.2.12-b140109.1041.jar;C:\\Users\\abbey\\.m2\\repository\\org\\glassfish\\jaxb\\txw2\\2.2.11\\txw2-2.2.11.jar;C:\\Users\\abbey\\.m2\\repository\\com\\sun\\istack\\istack-commons-runtime\\2.2\\istack-commons-runtime-2.2.jar;C:\\Users\\abbey\\.m2\\repository\\stax\\stax-api\\1.0.1\\stax-api-1.0.1.jar;C:\\Users\\abbey\\.m2\\repository\\javax\\activation\\activation\\1.1\\activation-1.1.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlcleaner\\htmlcleaner\\2.21\\htmlcleaner-2.21.jar;C:\\Users\\abbey\\.m2\\repository\\org\\jdom\\jdom2\\2.0.5\\jdom2-2.0.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\antlr4\\4.5\\antlr4-4.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\antlr4-runtime\\4.5\\antlr4-runtime-4.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\abego\\treelayout\\org.abego.treelayout.core\\1.0.1\\org.abego.treelayout.core-1.0.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\antlr-runtime\\3.5.2\\antlr-runtime-3.5.2.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\ST4\\4.0.8\\ST4-4.0.8.jar;C:\\Users\\abbey\\.m2\\repository\\eu\\bitwalker\\UserAgentUtils\\1.20\\UserAgentUtils-1.20.jar;C:\\Users\\abbey\\.m2\\repository\\com\\jayway\\jsonpath\\json-path\\2.0.0\\json-path-2.0.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\slf4j\\slf4j-api\\1.7.10\\slf4j-api-1.7.10.jar;C:\\Users\\abbey\\.m2\\repository\\net\\minidev\\json-smart\\2.1.1\\json-smart-2.1.1.jar;C:\\Users\\abbey\\.m2\\repository\\net\\minidev\\asm\\1.0.2\\asm-1.0.2.jar;C:\\Users\\abbey\\.m2\\repository\\asm\\asm\\3.3.1\\asm-3.3.1.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfectomobile\\intellij-connector\\10.10.0.1\\intellij-connector-10.10.0.1.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-testng\\2.2.4\\reportium-testng-2.2.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-java\\2.2.4\\reportium-java-2.2.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfectomobile\\pm-webdriver\\10.10.0.4\\pm-webdriver-10.10.0.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfectomobile\\http-client\\10.10.0.4\\http-client-10.10.0.4.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-java\\1.2.5\\cucumber-java-1.2.5.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-core\\1.2.5\\cucumber-core-1.2.5.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-html\\0.2.3\\cucumber-html-0.2.3.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-jvm-deps\\1.0.5\\cucumber-jvm-deps-1.0.5.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\gherkin\\2.12.2\\gherkin-2.12.2.jar;C:\\Users\\abbey\\.m2\\repository\\com\\xframium\\xframium-serialization\\2.0.6\\xframium-serialization-2.0.6.jar;C:\\Users\\abbey\\.m2\\repository\\org\\json\\json\\20160212\\json-20160212.jar;C:\\Users\\abbey\\.m2\\repository\\javax\\mail\\mail\\1.5.0-b01\\mail-1.5.0-b01.jar;C:\\Users\\abbey\\.m2\\repository\\com\\joestelmach\\natty\\0.12\\natty-0.12.jar;C:\\Users\\abbey\\.m2\\repository\\org\\mnode\\ical4j\\ical4j\\1.0.2\\ical4j-1.0.2.jar;C:\\Users\\abbey\\.m2\\repository\\commons-lang\\commons-lang\\2.6\\commons-lang-2.6.jar;C:\\Users\\abbey\\.m2\\repository\\backport-util-concurrent\\backport-util-concurrent\\3.1\\backport-util-concurrent-3.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\xframium\\alm\\1.0.4\\alm-1.0.4.jar;C:\\Users\\abbey\\.m2\\repository\\org\\slf4j\\slf4j-jdk14\\1.7.25\\slf4j-jdk14-1.7.25.jar;C:\\Users\\abbey\\.m2\\repository\\org\\xframium\\jira\\1.0.2\\jira-1.0.2.jar;C:\\Users\\abbey\\.m2\\repository\\com\\googlecode\\libphonenumber\\libphonenumber\\8.8.4\\libphonenumber-8.8.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\deque\\axe-selenium\\2.1\\axe-selenium-2.1.jar",
        "java.vm.vendor": "Oracle Corporation",
        "sun.arch.data.model": "64",
        "user.variant": "",
        "java.vendor.url": "http://java.oracle.com/",
        "user.timezone": "Europe/London",
        "__userName": "",
        "os.name": "Windows 10",
        "java.vm.specification.version": "1.8",
        "user.country": "GB",
        "sun.java.launcher": "SUN_STANDARD",
        "sun.boot.library.path": "C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\bin",
        "sun.java.command": "org.xframium.driver.TestDriver C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\driverConfig.xml",
        "sun.cpu.endian": "little",
        "user.home": "C:\\Users\\abbey",
        "user.language": "en",
        "java.specification.vendor": "Oracle Corporation",
        "java.home": "C:\\Program Files\\Java\\jdk1.8.0_73\\jre",
        "file.separator": "\\",
        "line.separator": "\r\n",
        "java.vm.specification.vendor": "Oracle Corporation",
        "java.specification.name": "Java Platform API Specification",
        "java.awt.graphicsenv": "sun.awt.Win32GraphicsEnvironment",
        "__cloudUrl": "https://127.0.0.1:4444",
        "sun.boot.class.path": "C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\resources.jar;C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\rt.jar;C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\sunrsasign.jar;C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\jsse.jar;C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\jce.jar;C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\charsets.jar;C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\jfr.jar;C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\classes",
        "user.script": "",
        "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
        "java.runtime.version": "1.8.0_73-b02",
        "user.name": "abbey",
        "path.separator": ";",
        "os.version": "10.0",
        "java.endorsed.dirs": "C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\endorsed",
        "java.runtime.name": "Java(TM) SE Runtime Environment",
        "file.encoding": "Cp1252",
        "__password": "",
        "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
        "driver.retryCount": "0",
        "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
        "java.io.tmpdir": "C:\\Users\\abbey\\AppData\\Local\\Temp\\",
        "java.version": "1.8.0_73",
        "user.dir": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\xframium-driver",
        "os.arch": "amd64",
        "java.vm.specification.name": "Java Virtual Machine Specification",
        "java.awt.printerjob": "sun.awt.windows.WPrinterJob",
        "sun.os.patch.level": "",
        "java.library.path": "C:\\Program Files\\Java\\jdk1.8.0_73\\bin;C:\\WINDOWS\\Sun\\Java\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:/Program Files/Java/jdk1.8.0_73/jre/bin/server;C:/Program Files/Java/jdk1.8.0_73/jre/bin;C:/Program Files/Java/jdk1.8.0_73/jre/lib/amd64;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Common Files\\Adobe\\AGL;C:\\Program Files (x86)\\MySQL\\MySQL Utilities\\;C:\\Program Files (x86)\\MySQL\\MySQL Utilities\\Doctrine extensions for PHP\\;C:\\Users\\abbey\\Desktop\\xampp\\php;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files (x86)\\GtkSharp\\2.12\\bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\apache-maven-3.6.1\\bin;C:\\Users\\abbey\\eclipse-xFramiumWorkspace\\Selenium_Java\\drivers\\iedriver;C:\\Users\\abbey\\eclipse-xFramiumWorkspace\\Selenium_Java\\drivers\\chrome\\chromedriver.exe;C:\\Users\\abbey\\eclipse-xFramiumWorkspace\\Selenium_Java\\drivers\\geckodriver\\geckodriver.exe;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Python37;C:\\Python37\\Scripts;C:\\Python37\\Lib\\site-packages\\selenium\\webdriver;C:\\Python37\\Scripts\\;C:\\Python37\\;C:\\Users\\abbey\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\abbey\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2019.2\\bin;;;C:\\Users\\abbey\\Desktop;;.",
        "java.vm.info": "mixed mode",
        "java.vendor": "Oracle Corporation",
        "java.vm.version": "25.73-b02",
        "java.ext.dirs": "C:\\Program Files\\Java\\jdk1.8.0_73\\jre\\lib\\ext;C:\\WINDOWS\\Sun\\Java\\lib\\ext",
        "sun.io.unicode.encoding": "UnicodeLittle",
        "java.class.version": "52.0"
    },
    "deviceMap": {},
    "testException": "null",
    "stepList": [
        {
            "locatorResult": "null",
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "customMessage": "null",
            "step": {
                "deviceTags": "null",
                "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
                "threshold": "0",
                "sFailure": "ERROR",
                "pageName": "null",
                "context": "null",
                "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                "waitFor": "null",
                "validation": "null",
                "reportingTokens": [],
                "image": "null",
                "timed": false,
                "active": true,
                "stepList": [],
                "version": "null",
                "DATA_PATTERN": "data\\{(\\w*)\\}",
                "name": "Login_Function",
                "parameterList": [],
                "device": "null",
                "successReport": "null",
                "failureReport": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                "siteName": "null",
                "description": "",
                "poi": "null",
                "tagNames": "null",
                "trace": false,
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "tokenList": [],
                "featureId": "11",
                "startAt": false,
                "kwName": "Call Test/Function",
                "numberGenerator": "java.util.Random@30ea2300",
                "inverse": false,
                "os": "null",
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
                "kw": "CALL2",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "allowMultiple": false,
                "dataTable": "null",
                "appContext": "null",
                "category": "Flow Control",
                "orMapping": false,
                "waitTime": "0"
            },
            "startTime": {
                "dateTime": "11/22/2019-20:50:56",
                "dateOnly": "11/22/2019",
                "timeOnly": "20:50:56",
                "raw": 1574455856726
            },
            "endTime": {
                "dateTime": "11/22/2019-20:50:59",
                "dateOnly": "11/22/2019",
                "timeOnly": "20:50:59",
                "raw": 1574455859844
            },
            "stepList": [
                {
                    "locatorResult": "null",
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to work with browser windows",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-browser",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "null",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "MAXIMIZE",
                        "parameterList": [],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "9",
                        "startAt": false,
                        "kwName": "Browser Operations",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSBrowser",
                        "kw": "BROWSER",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Web",
                        "orMapping": false,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:56",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:56",
                        "raw": 1574455856728
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:56",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:56",
                        "raw": 1574455856883
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "287",
                        "locator": "By.xpath: //div[@class='login-logo']//a//img"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["45"],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to wait for an element to be exist in a certain state",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-waitfor",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSLoginPage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "CloudScl_img.VISIBLE",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "45"
                        }],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "55",
                        "startAt": false,
                        "kwName": "Wait for element",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSWaitFor",
                        "kw": "WAIT_FOR",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:56",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:56",
                        "raw": 1574455856886
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857327
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "48",
                        "locator": "By.xpath: //input[@name='username']"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["45"],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to wait for an element to be exist in a certain state",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-waitfor",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSLoginPage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Username_txtbox.CLICKABLE",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "45"
                        }],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "55",
                        "startAt": false,
                        "kwName": "Wait for element",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSWaitFor",
                        "kw": "WAIT_FOR",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857327
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857464
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "20",
                        "locator": "By.xpath: //input[@name='username']"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["admin"],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSLoginPage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Username_txtbox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "DATA",
                            "tokenList": [],
                            "value": "LoginCredentials.UserName"
                        }],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "45",
                        "startAt": false,
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "kw": "SET",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857464
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857719
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "30",
                        "locator": "By.xpath: //input[@name='password']"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["demo123"],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSLoginPage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Password_txtbox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "DATA",
                            "tokenList": [],
                            "value": "LoginCredentials.Password"
                        }],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "45",
                        "startAt": false,
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "kw": "SET",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857719
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857932
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "25",
                        "locator": "By.xpath: //button[@class='btn btn-lg btn-block btn-flat login-button']"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to click on the center of the named element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-click",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSLoginPage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Signin_btn",
                        "parameterList": [],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "13",
                        "startAt": false,
                        "kwName": "Click",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSClick",
                        "kw": "CLICK",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:57",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:57",
                        "raw": 1574455857932
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:59",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:59",
                        "raw": 1574455859843
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": "null",
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "null",
                        "validationType": "null",
                        "kwHelp": "null",
                        "threshold": "0",
                        "sFailure": "null",
                        "pageName": "null",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": false,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Return from Login_Function",
                        "parameterList": [],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "Return from Login_Function",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "0",
                        "startAt": false,
                        "kwName": "N/A",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.SyntheticStep",
                        "kw": "CALLBACK",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Other",
                        "orMapping": false,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:59",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:59",
                        "raw": 1574455859844
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:59",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:59",
                        "raw": 1574455859844
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                }
            ],
            "message": "null",
            "timingMap": {},
            "stepStatus": "SUCCESS"
        },
        {
            "locatorResult": "null",
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "customMessage": "null",
            "step": {
                "deviceTags": "null",
                "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
                "threshold": "0",
                "sFailure": "ERROR",
                "pageName": "null",
                "context": "null",
                "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                "waitFor": "null",
                "validation": "null",
                "reportingTokens": [],
                "image": "null",
                "timed": false,
                "active": true,
                "stepList": [],
                "version": "null",
                "DATA_PATTERN": "data\\{(\\w*)\\}",
                "name": "Logout_Function",
                "parameterList": [],
                "device": "null",
                "successReport": "null",
                "failureReport": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                "siteName": "null",
                "description": "",
                "poi": "null",
                "tagNames": "null",
                "trace": false,
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "tokenList": [],
                "featureId": "11",
                "startAt": false,
                "kwName": "Call Test/Function",
                "numberGenerator": "java.util.Random@30ea2300",
                "inverse": false,
                "os": "null",
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
                "kw": "CALL2",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "allowMultiple": false,
                "dataTable": "null",
                "appContext": "null",
                "category": "Flow Control",
                "orMapping": false,
                "waitTime": "0"
            },
            "startTime": {
                "dateTime": "11/22/2019-20:50:59",
                "dateOnly": "11/22/2019",
                "timeOnly": "20:50:59",
                "raw": 1574455859844
            },
            "endTime": {
                "dateTime": "11/22/2019-20:51:03",
                "dateOnly": "11/22/2019",
                "timeOnly": "20:51:03",
                "raw": 1574455863138
            },
            "stepList": [
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "28",
                        "locator": "By.xpath: (//span[contains(text(),'Mr. admin')])[1]"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["45"],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to wait for an element to be exist in a certain state",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-waitfor",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSHomePage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "MrAdmin_topnav.CLICKABLE",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "45"
                        }],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "55",
                        "startAt": false,
                        "kwName": "Wait for element",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSWaitFor",
                        "kw": "WAIT_FOR",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:59",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:59",
                        "raw": 1574455859845
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:50:59",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:59",
                        "raw": 1574455859942
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "27",
                        "locator": "By.xpath: (//span[contains(text(),'Mr. admin')])[1]"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to click on the center of the named element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-click",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSHomePage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "MrAdmin_topnav",
                        "parameterList": [],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "13",
                        "startAt": false,
                        "kwName": "Click",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSClick",
                        "kw": "CLICK",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:50:59",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:50:59",
                        "raw": 1574455859942
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:51:00",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:51:00",
                        "raw": 1574455860379
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "28",
                        "locator": "By.xpath: //li[contains(@class,'user-footer')]//div[1]//a[1]//div[1]"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["45"],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to wait for an element to be exist in a certain state",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-waitfor",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSHomePage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Logout_link.CLICKABLE",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "45"
                        }],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "55",
                        "startAt": false,
                        "kwName": "Wait for element",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSWaitFor",
                        "kw": "WAIT_FOR",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:51:00",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:51:00",
                        "raw": 1574455860379
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:51:00",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:51:00",
                        "raw": 1574455860479
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": [{
                        "success": true,
                        "time": "25",
                        "locator": "By.xpath: //li[contains(@class,'user-footer')]//div[1]//a[1]//div[1]"
                    }],
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "Allows the script to click on the center of the named element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-click",
                        "threshold": "0",
                        "sFailure": "ERROR",
                        "pageName": "CSHomePage",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": true,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Logout_link",
                        "parameterList": [],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "13",
                        "startAt": false,
                        "kwName": "Click",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSClick",
                        "kw": "CLICK",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:51:00",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:51:00",
                        "raw": 1574455860479
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:51:03",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:51:03",
                        "raw": 1574455863138
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "locatorResult": "null",
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [],
                    "customMessage": "null",
                    "step": {
                        "deviceTags": "null",
                        "kwDescription": "null",
                        "validationType": "null",
                        "kwHelp": "null",
                        "threshold": "0",
                        "sFailure": "null",
                        "pageName": "null",
                        "context": "null",
                        "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                        "waitFor": "null",
                        "validation": "null",
                        "reportingTokens": [],
                        "image": "null",
                        "timed": false,
                        "active": false,
                        "stepList": [],
                        "version": "null",
                        "DATA_PATTERN": "data\\{(\\w*)\\}",
                        "name": "Return from Logout_Function",
                        "parameterList": [],
                        "device": "null",
                        "successReport": "null",
                        "failureReport": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@23420eb2",
                        "siteName": "null",
                        "description": "Return from Logout_Function",
                        "poi": "null",
                        "tagNames": "null",
                        "trace": false,
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "tokenList": [],
                        "featureId": "0",
                        "startAt": false,
                        "kwName": "N/A",
                        "numberGenerator": "java.util.Random@30ea2300",
                        "inverse": false,
                        "os": "null",
                        "kwImpl": "org.xframium.page.keyWord.step.SyntheticStep",
                        "kw": "CALLBACK",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "allowMultiple": false,
                        "dataTable": "null",
                        "appContext": "null",
                        "category": "Other",
                        "orMapping": false,
                        "waitTime": "0"
                    },
                    "startTime": {
                        "dateTime": "11/22/2019-20:51:03",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:51:03",
                        "raw": 1574455863138
                    },
                    "endTime": {
                        "dateTime": "11/22/2019-20:51:03",
                        "dateOnly": "11/22/2019",
                        "timeOnly": "20:51:03",
                        "raw": 1574455863138
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                }
            ],
            "message": "null",
            "timingMap": {},
            "stepStatus": "SUCCESS"
        }
    ],
    "sessionId": "03acad6f-ddba-439d-9027-7ebe3ef488ed",
    "message": "null",
    "callMap": {},
    "currentStep": "null",
    "featureList": [
        "11",
        "9",
        "55",
        "55",
        "45",
        "45",
        "13",
        "11",
        "55",
        "13",
        "55",
        "13"
    ],
    "endTime": {
        "dateTime": "11/22/2019-20:51:03",
        "dateOnly": "11/22/2019",
        "timeOnly": "20:51:03",
        "raw": 1574455863138
    },
    "folderName": "Windows chrome\\TC01_ValidLogin",
    "cloudDescriptor": {
        "hostName": "127.0.0.1:4444",
        "proxyPort": "null",
        "password": "",
        "keepAlive": "null",
        "deviceAction": "null",
        "provider": "SELENIUM",
        "gridInstance": "null",
        "name": "local",
        "description": "",
        "userName": "",
        "proxyHost": "null",
        "gesture": "null"
    },
    "contextMap": {
        "_device.browserVersion": "null",
        "_device.phoneNumber": "null",
        "_device.environment": "WINDOWS 10 Chrome",
        "_device.name": "Chrome",
        "_device.cloud": "local",
        "_device.manufacturer": "Microsoft Corporation",
        "_device.osVersion": "10",
        "_device.resolution": "1050 x 708",
        "_device.model": "null",
        "_device.browserName": "Chrome",
        "XF_TEST_STATUS": "PASSED",
        "_device.os": "WINDOWS"
    },
    "device": {
        "capabilities": {},
        "os": "WINDOWS",
        "active": false,
        "deviceLock": "java.util.concurrent.Semaphore@3df0c80d[Permits = 1]",
        "deviceName": "Chrome",
        "resolution": "1050 x 708",
        "capList": [],
        "driverType": "WEB",
        "tagNames": [],
        "manufacturer": "Microsoft Corporation",
        "cloud": "local",
        "environment": "WINDOWS 10 Chrome",
        "phoneNumber": "null",
        "osVersion": "10",
        "browserVersion": "null",
        "availableDevices": "1",
        "browserName": "Chrome",
        "model": "null",
        "cachedString": "null",
        "key": "Chrome"
    },
    "messageDetail": "null"
}};