var testData = {"pageData": {
    "exceptionType": "CLOUD",
    "aut": "null",
    "timerStart": "0",
    "elementUsageMap": {},
    "failedStep": "null",
    "elementUsage": [],
    "iterationCount": "0",
    "csvOutput": "",
    "testStatus": "FAILED",
    "dataMap": "null",
    "pageMap": "null",
    "pageUsageMap": {},
    "timerName": "null",
    "inStepListener": false,
    "startTime": {
        "dateTime": "02/29/2020-17:20:16",
        "dateOnly": "02/29/2020",
        "timeOnly": "17:20:16",
        "raw": 1582996816646
    },
    "xFID": "f3f3fbc8-d922-4b4c-8bc1-bd855119563c",
    "testName": "TC01_ValidLogin",
    "dC": "null",
    "executionParameters": {
        "ALL_IN_ONE": "enabled",
        "ALL_IN_ONE_PATH": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\02-29_17-20-16-678\\Windows chrome\\TC01_ValidLogin\\allInOne.html",
        "ALL_IN_ONE_ABS": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\02-29_17-20-16-678\\Windows chrome\\TC01_ValidLogin\\allInOne.html",
        "ALL_IN_ONE_FILE": "allInOne.html",
        "CONSOLE_LOG": "enabled",
        "CONSOLE_LOG_ABS": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\02-29_17-20-16-678\\Windows chrome\\TC01_ValidLogin\\console.txt",
        "CONSOLE_LOG_FILE": "console.txt",
        "CONSOLE_LOG_PATH": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output\\02-29_17-20-16-678\\Windows chrome\\TC01_ValidLogin\\console.txt"
    },
    "c": "null",
    "test": {
        "deviceTags": "null",
        "outputPage": "null",
        "severity": "0",
        "timed": false,
        "reliesOn": "null",
        "os": "null",
        "contentKeys": [""],
        "log": "org.apache.commons.logging.impl.Jdk14Logger@48deb0cd",
        "inputPage": "null",
        "count": "0",
        "active": true,
        "description": "null",
        "threshold": "0",
        "expectedParameters": [],
        "stepList": [
            {
                "deviceTags": "null",
                "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
                "threshold": "0",
                "sFailure": "ERROR",
                "pageName": "null",
                "context": "null",
                "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                "waitFor": "null",
                "validation": "null",
                "reportingTokens": [],
                "image": "null",
                "timed": false,
                "active": true,
                "stepList": [],
                "version": "null",
                "DATA_PATTERN": "data\\{(\\w*)\\}",
                "name": "Login_Function",
                "parameterList": [],
                "device": "null",
                "successReport": "null",
                "failureReport": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@5beea03f",
                "siteName": "null",
                "description": "",
                "poi": "null",
                "tagNames": "null",
                "trace": false,
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "tokenList": [],
                "featureId": "11",
                "startAt": false,
                "kwName": "Call Test/Function",
                "numberGenerator": "java.util.Random@55b8e599",
                "inverse": false,
                "os": "null",
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
                "kw": "CALL2",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "allowMultiple": false,
                "dataTable": "null",
                "appContext": "null",
                "category": "Flow Control",
                "orMapping": false,
                "waitTime": "0"
            },
            {
                "deviceTags": "null",
                "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
                "threshold": "0",
                "sFailure": "ERROR",
                "pageName": "null",
                "context": "null",
                "TOKEN_REGEX": "\\{([^\\}]*)\\}",
                "waitFor": "null",
                "validation": "null",
                "reportingTokens": [],
                "image": "null",
                "timed": false,
                "active": true,
                "stepList": [],
                "version": "null",
                "DATA_PATTERN": "data\\{(\\w*)\\}",
                "name": "Logout_Function",
                "parameterList": [],
                "device": "null",
                "successReport": "null",
                "failureReport": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@5beea03f",
                "siteName": "null",
                "description": "",
                "poi": "null",
                "tagNames": "null",
                "trace": false,
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "tokenList": [],
                "featureId": "11",
                "startAt": false,
                "kwName": "Call Test/Function",
                "numberGenerator": "java.util.Random@55b8e599",
                "inverse": false,
                "os": "null",
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
                "kw": "CALL2",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "allowMultiple": false,
                "dataTable": "null",
                "appContext": "null",
                "category": "Flow Control",
                "orMapping": false,
                "waitTime": "0"
            }
        ],
        "priority": "0",
        "testTags": [""],
        "mode": "null",
        "operationList": "null",
        "trace": "OFF",
        "linkId": "null",
        "dataDriver": "null",
        "name": "TC01_ValidLogin",
        "dataProviders": ["LoginCredentials.TestUser_One"]
    },
    "sPMap": {
        "__outputFolder": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\test-output",
        "sun.desktop": "windows",
        "awt.toolkit": "sun.awt.windows.WToolkit",
        "file.encoding.pkg": "sun.io",
        "java.specification.version": "1.8",
        "sun.cpu.isalist": "amd64",
        "sun.jnu.encoding": "Cp1252",
        "java.class.path": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\xframium-driver\\bin;C:\\Users\\abbey\\.m2\\repository\\commons-logging\\commons-logging\\1.1.1\\commons-logging-1.1.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\testng\\testng\\6.9.10\\testng-6.9.10.jar;C:\\Users\\abbey\\.m2\\repository\\com\\beust\\jcommander\\1.48\\jcommander-1.48.jar;C:\\Users\\abbey\\.m2\\repository\\org\\beanshell\\bsh\\2.0b4\\bsh-2.0b4.jar;C:\\Users\\abbey\\.m2\\repository\\org\\xframium\\xframium-java\\1.0.21\\xframium-java-1.0.21.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\poi\\poi-ooxml\\3.11\\poi-ooxml-3.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\poi\\poi\\3.11\\poi-3.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\poi\\poi-ooxml-schemas\\3.11\\poi-ooxml-schemas-3.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\xmlbeans\\xmlbeans\\2.6.0\\xmlbeans-2.6.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-java\\3.13.0\\selenium-java-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-chrome-driver\\3.13.0\\selenium-chrome-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-edge-driver\\3.13.0\\selenium-edge-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-firefox-driver\\3.13.0\\selenium-firefox-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-ie-driver\\3.13.0\\selenium-ie-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-opera-driver\\3.13.0\\selenium-opera-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-remote-driver\\3.13.0\\selenium-remote-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-safari-driver\\3.13.0\\selenium-safari-driver-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-support\\3.13.0\\selenium-support-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\net\\bytebuddy\\byte-buddy\\1.8.3\\byte-buddy-1.8.3.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\commons\\commons-exec\\1.3\\commons-exec-1.3.jar;C:\\Users\\abbey\\.m2\\repository\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\code\\gson\\gson\\2.8.4\\gson-2.8.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\guava\\guava\\25.0-jre\\guava-25.0-jre.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\code\\findbugs\\jsr305\\1.3.9\\jsr305-1.3.9.jar;C:\\Users\\abbey\\.m2\\repository\\org\\checkerframework\\checker-compat-qual\\2.0.0\\checker-compat-qual-2.0.0.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\errorprone\\error_prone_annotations\\2.1.3\\error_prone_annotations-2.1.3.jar;C:\\Users\\abbey\\.m2\\repository\\com\\google\\j2objc\\j2objc-annotations\\1.1\\j2objc-annotations-1.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\codehaus\\mojo\\animal-sniffer-annotations\\1.14\\animal-sniffer-annotations-1.14.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\httpcomponents\\httpclient\\4.5.5\\httpclient-4.5.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\httpcomponents\\httpcore\\4.4.9\\httpcore-4.4.9.jar;C:\\Users\\abbey\\.m2\\repository\\com\\squareup\\okhttp3\\okhttp\\3.10.0\\okhttp-3.10.0.jar;C:\\Users\\abbey\\.m2\\repository\\com\\squareup\\okio\\okio\\1.14.1\\okio-1.14.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-api\\3.13.0\\selenium-api-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-server\\3.13.0\\selenium-server-3.13.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.7\\commons-lang3-3.7.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\commons\\commons-text\\1.1\\commons-text-1.1.jar;C:\\Users\\abbey\\.m2\\repository\\commons-io\\commons-io\\2.6\\commons-io-2.6.jar;C:\\Users\\abbey\\.m2\\repository\\commons-net\\commons-net\\3.6\\commons-net-3.6.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit\\2.30\\htmlunit-2.30.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit-core-js\\2.28\\htmlunit-core-js-2.28.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit-cssparser\\1.0.0\\htmlunit-cssparser-1.0.0.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlunit\\neko-htmlunit\\2.30\\neko-htmlunit-2.30.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\httpcomponents\\httpmime\\4.5.5\\httpmime-4.5.5.jar;C:\\Users\\abbey\\.m2\\repository\\net\\jcip\\jcip-annotations\\1.0\\jcip-annotations-1.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\jetty-repacked\\9.4.7.v20171121\\jetty-repacked-9.4.7.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-client\\9.4.7.v20170914\\jetty-client-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-http\\9.4.8.v20171121\\jetty-http-9.4.8.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-io\\9.4.8.v20171121\\jetty-io-9.4.8.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-util\\9.4.8.v20171121\\jetty-util-9.4.8.v20171121.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\jetty-xml\\9.4.7.v20170914\\jetty-xml-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\seleniumhq\\selenium\\htmlunit-driver\\2.30.0\\htmlunit-driver-2.30.0.jar;C:\\Users\\abbey\\.m2\\repository\\javax\\servlet\\javax.servlet-api\\3.1.0\\javax.servlet-api-3.1.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-api\\9.4.7.v20170914\\websocket-api-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-client\\9.4.7.v20170914\\websocket-client-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-common\\9.4.7.v20170914\\websocket-common-9.4.7.v20170914.jar;C:\\Users\\abbey\\.m2\\repository\\xalan\\serializer\\2.7.2\\serializer-2.7.2.jar;C:\\Users\\abbey\\.m2\\repository\\xalan\\xalan\\2.7.2\\xalan-2.7.2.jar;C:\\Users\\abbey\\.m2\\repository\\xerces\\xercesImpl\\2.11.0\\xercesImpl-2.11.0.jar;C:\\Users\\abbey\\.m2\\repository\\xml-apis\\xml-apis\\1.4.01\\xml-apis-1.4.01.jar;C:\\Users\\abbey\\.m2\\repository\\org\\yaml\\snakeyaml\\1.19\\snakeyaml-1.19.jar;C:\\Users\\abbey\\.m2\\repository\\org\\reflections\\reflections\\0.9.11\\reflections-0.9.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\javassist\\javassist\\3.21.0-GA\\javassist-3.21.0-GA.jar;C:\\Users\\abbey\\.m2\\repository\\io\\appium\\java-client\\6.1.0\\java-client-6.1.0.jar;C:\\Users\\abbey\\.m2\\repository\\cglib\\cglib\\3.2.6\\cglib-3.2.6.jar;C:\\Users\\abbey\\.m2\\repository\\org\\ow2\\asm\\asm\\6.0\\asm-6.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\ant\\ant\\1.9.6\\ant-1.9.6.jar;C:\\Users\\abbey\\.m2\\repository\\org\\apache\\ant\\ant-launcher\\1.9.6\\ant-launcher-1.9.6.jar;C:\\Users\\abbey\\.m2\\repository\\commons-validator\\commons-validator\\1.6\\commons-validator-1.6.jar;C:\\Users\\abbey\\.m2\\repository\\commons-beanutils\\commons-beanutils\\1.9.2\\commons-beanutils-1.9.2.jar;C:\\Users\\abbey\\.m2\\repository\\commons-digester\\commons-digester\\1.8.1\\commons-digester-1.8.1.jar;C:\\Users\\abbey\\.m2\\repository\\commons-collections\\commons-collections\\3.2.2\\commons-collections-3.2.2.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-context\\5.0.5.RELEASE\\spring-context-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-aop\\5.0.5.RELEASE\\spring-aop-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-beans\\5.0.5.RELEASE\\spring-beans-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-core\\5.0.5.RELEASE\\spring-core-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-jcl\\5.0.5.RELEASE\\spring-jcl-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\springframework\\spring-expression\\5.0.5.RELEASE\\spring-expression-5.0.5.RELEASE.jar;C:\\Users\\abbey\\.m2\\repository\\org\\aspectj\\aspectjweaver\\1.9.1\\aspectjweaver-1.9.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\openpnp\\opencv\\3.2.0-1\\opencv-3.2.0-1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-runtime\\2.2.11\\jaxb-runtime-2.2.11.jar;C:\\Users\\abbey\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-core\\2.2.11\\jaxb-core-2.2.11.jar;C:\\Users\\abbey\\.m2\\repository\\com\\sun\\istack\\istack-commons-runtime\\2.2\\istack-commons-runtime-2.2.jar;C:\\Users\\abbey\\.m2\\repository\\stax\\stax-api\\1.0.1\\stax-api-1.0.1.jar;C:\\Users\\abbey\\.m2\\repository\\javax\\activation\\activation\\1.1\\activation-1.1.jar;C:\\Users\\abbey\\.m2\\repository\\net\\sourceforge\\htmlcleaner\\htmlcleaner\\2.21\\htmlcleaner-2.21.jar;C:\\Users\\abbey\\.m2\\repository\\org\\jdom\\jdom2\\2.0.5\\jdom2-2.0.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\antlr4\\4.5\\antlr4-4.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\antlr4-runtime\\4.5\\antlr4-runtime-4.5.jar;C:\\Users\\abbey\\.m2\\repository\\org\\abego\\treelayout\\org.abego.treelayout.core\\1.0.1\\org.abego.treelayout.core-1.0.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\antlr-runtime\\3.5.2\\antlr-runtime-3.5.2.jar;C:\\Users\\abbey\\.m2\\repository\\org\\antlr\\ST4\\4.0.8\\ST4-4.0.8.jar;C:\\Users\\abbey\\.m2\\repository\\eu\\bitwalker\\UserAgentUtils\\1.20\\UserAgentUtils-1.20.jar;C:\\Users\\abbey\\.m2\\repository\\com\\jayway\\jsonpath\\json-path\\2.0.0\\json-path-2.0.0.jar;C:\\Users\\abbey\\.m2\\repository\\org\\slf4j\\slf4j-api\\1.7.10\\slf4j-api-1.7.10.jar;C:\\Users\\abbey\\.m2\\repository\\net\\minidev\\json-smart\\2.1.1\\json-smart-2.1.1.jar;C:\\Users\\abbey\\.m2\\repository\\net\\minidev\\asm\\1.0.2\\asm-1.0.2.jar;C:\\Users\\abbey\\.m2\\repository\\asm\\asm\\3.3.1\\asm-3.3.1.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfectomobile\\intellij-connector\\10.10.0.1\\intellij-connector-10.10.0.1.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-testng\\2.2.4\\reportium-testng-2.2.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-java\\2.2.4\\reportium-java-2.2.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfectomobile\\pm-webdriver\\10.10.0.4\\pm-webdriver-10.10.0.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\perfectomobile\\http-client\\10.10.0.4\\http-client-10.10.0.4.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-java\\1.2.5\\cucumber-java-1.2.5.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-core\\1.2.5\\cucumber-core-1.2.5.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-html\\0.2.3\\cucumber-html-0.2.3.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\cucumber-jvm-deps\\1.0.5\\cucumber-jvm-deps-1.0.5.jar;C:\\Users\\abbey\\.m2\\repository\\info\\cukes\\gherkin\\2.12.2\\gherkin-2.12.2.jar;C:\\Users\\abbey\\.m2\\repository\\com\\xframium\\xframium-serialization\\2.0.6\\xframium-serialization-2.0.6.jar;C:\\Users\\abbey\\.m2\\repository\\org\\json\\json\\20160212\\json-20160212.jar;C:\\Users\\abbey\\.m2\\repository\\javax\\mail\\mail\\1.5.0-b01\\mail-1.5.0-b01.jar;C:\\Users\\abbey\\.m2\\repository\\com\\joestelmach\\natty\\0.12\\natty-0.12.jar;C:\\Users\\abbey\\.m2\\repository\\org\\mnode\\ical4j\\ical4j\\1.0.2\\ical4j-1.0.2.jar;C:\\Users\\abbey\\.m2\\repository\\commons-lang\\commons-lang\\2.6\\commons-lang-2.6.jar;C:\\Users\\abbey\\.m2\\repository\\backport-util-concurrent\\backport-util-concurrent\\3.1\\backport-util-concurrent-3.1.jar;C:\\Users\\abbey\\.m2\\repository\\org\\xframium\\alm\\1.0.4\\alm-1.0.4.jar;C:\\Users\\abbey\\.m2\\repository\\org\\slf4j\\slf4j-jdk14\\1.7.25\\slf4j-jdk14-1.7.25.jar;C:\\Users\\abbey\\.m2\\repository\\org\\xframium\\jira\\1.0.2\\jira-1.0.2.jar;C:\\Users\\abbey\\.m2\\repository\\com\\googlecode\\libphonenumber\\libphonenumber\\8.8.4\\libphonenumber-8.8.4.jar;C:\\Users\\abbey\\.m2\\repository\\com\\deque\\axe-selenium\\2.1\\axe-selenium-2.1.jar",
        "java.vm.vendor": "Oracle Corporation",
        "sun.arch.data.model": "64",
        "user.variant": "",
        "java.vendor.url": "http://java.oracle.com/",
        "user.timezone": "Europe/London",
        "__userName": "",
        "os.name": "Windows 10",
        "java.vm.specification.version": "1.8",
        "user.country": "GB",
        "sun.java.launcher": "SUN_STANDARD",
        "sun.boot.library.path": "C:\\Program Files\\Java\\jre1.8.0_241\\bin",
        "sun.java.command": "org.xframium.driver.TestDriver C:\\Users\\abbey\\Desktop\\2019-xFramium\\CloudSchool\\config\\driverConfig.xml",
        "sun.cpu.endian": "little",
        "user.home": "C:\\Users\\abbey",
        "user.language": "en",
        "java.specification.vendor": "Oracle Corporation",
        "java.home": "C:\\Program Files\\Java\\jre1.8.0_241",
        "file.separator": "\\",
        "line.separator": "\r\n",
        "java.vm.specification.vendor": "Oracle Corporation",
        "java.specification.name": "Java Platform API Specification",
        "java.awt.graphicsenv": "sun.awt.Win32GraphicsEnvironment",
        "__cloudUrl": "https://127.0.0.1:4444",
        "sun.boot.class.path": "C:\\Program Files\\Java\\jre1.8.0_241\\lib\\resources.jar;C:\\Program Files\\Java\\jre1.8.0_241\\lib\\rt.jar;C:\\Program Files\\Java\\jre1.8.0_241\\lib\\sunrsasign.jar;C:\\Program Files\\Java\\jre1.8.0_241\\lib\\jsse.jar;C:\\Program Files\\Java\\jre1.8.0_241\\lib\\jce.jar;C:\\Program Files\\Java\\jre1.8.0_241\\lib\\charsets.jar;C:\\Program Files\\Java\\jre1.8.0_241\\lib\\jfr.jar;C:\\Program Files\\Java\\jre1.8.0_241\\classes",
        "user.script": "",
        "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
        "java.runtime.version": "1.8.0_241-b07",
        "user.name": "abbey",
        "path.separator": ";",
        "os.version": "10.0",
        "java.endorsed.dirs": "C:\\Program Files\\Java\\jre1.8.0_241\\lib\\endorsed",
        "java.runtime.name": "Java(TM) SE Runtime Environment",
        "file.encoding": "Cp1252",
        "__password": "",
        "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
        "driver.retryCount": "0",
        "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
        "java.io.tmpdir": "C:\\Users\\abbey\\AppData\\Local\\Temp\\",
        "java.version": "1.8.0_241",
        "user.dir": "C:\\Users\\abbey\\Desktop\\2019-xFramium\\xframium-driver",
        "os.arch": "amd64",
        "java.vm.specification.name": "Java Virtual Machine Specification",
        "java.awt.printerjob": "sun.awt.windows.WPrinterJob",
        "sun.os.patch.level": "",
        "java.library.path": "C:\\Program Files\\Java\\jre1.8.0_241\\bin;C:\\WINDOWS\\Sun\\Java\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:/Program Files/Java/jre1.8.0_241/bin/server;C:/Program Files/Java/jre1.8.0_241/bin;C:/Program Files/Java/jre1.8.0_241/lib/amd64;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\abbey\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\abbey\\eclipse\\java-2019-06\\eclipse;;.",
        "java.vm.info": "mixed mode",
        "java.vendor": "Oracle Corporation",
        "java.vm.version": "25.241-b07",
        "java.ext.dirs": "C:\\Program Files\\Java\\jre1.8.0_241\\lib\\ext;C:\\WINDOWS\\Sun\\Java\\lib\\ext",
        "sun.io.unicode.encoding": "UnicodeLittle",
        "java.class.version": "52.0"
    },
    "deviceMap": {},
    "testException": "Could not connect to Google Chrome (Chrome)",
    "stepList": [{
        "locatorResult": "null",
        "throwable": "Could not connect to Google Chrome (Chrome)",
        "executionParameter": {},
        "parameterList": [],
        "customMessage": "null",
        "step": {
            "deviceTags": "null",
            "kwDescription": "null",
            "validationType": "null",
            "kwHelp": "null",
            "threshold": "0",
            "sFailure": "null",
            "pageName": "null",
            "context": "null",
            "TOKEN_REGEX": "\\{([^\\}]*)\\}",
            "waitFor": "null",
            "validation": "null",
            "reportingTokens": [],
            "image": "null",
            "timed": false,
            "active": false,
            "stepList": [],
            "version": "null",
            "DATA_PATTERN": "data\\{(\\w*)\\}",
            "name": "TC01_ValidLogin",
            "parameterList": [],
            "device": "null",
            "successReport": "null",
            "failureReport": "null",
            "natualLanguage": "null",
            "log": "org.apache.commons.logging.impl.Jdk14Logger@5beea03f",
            "siteName": "null",
            "description": "null",
            "poi": "null",
            "tagNames": "null",
            "trace": false,
            "numberFormat": "java.text.DecimalFormat@674dc",
            "browser": "null",
            "tokenList": [],
            "featureId": "0",
            "startAt": false,
            "kwName": "N/A",
            "numberGenerator": "java.util.Random@55b8e599",
            "inverse": false,
            "os": "null",
            "kwImpl": "org.xframium.page.keyWord.step.SyntheticStep",
            "kw": "TEST",
            "breakpoint": false,
            "fork": false,
            "linkId": "null",
            "allowMultiple": false,
            "dataTable": "null",
            "appContext": "null",
            "category": "Other",
            "orMapping": true,
            "waitTime": "0"
        },
        "startTime": {
            "dateTime": "02/29/2020-17:20:16",
            "dateOnly": "02/29/2020",
            "timeOnly": "17:20:16",
            "raw": 1582996816666
        },
        "endTime": {
            "dateTime": "02/29/2020-17:20:16",
            "dateOnly": "02/29/2020",
            "timeOnly": "17:20:16",
            "raw": 1582996816666
        },
        "stepList": [],
        "message": "Could not connect to Google Chrome (Chrome)",
        "timingMap": {},
        "stepStatus": "FAILURE"
    }],
    "sessionId": "null",
    "message": "Could not connect to Google Chrome (Chrome)",
    "callMap": {},
    "currentStep": "null",
    "featureList": [],
    "endTime": {
        "dateTime": "02/29/2020-17:20:16",
        "dateOnly": "02/29/2020",
        "timeOnly": "17:20:16",
        "raw": 1582996816666
    },
    "folderName": "Windows chrome\\TC01_ValidLogin",
    "cloudDescriptor": {
        "hostName": "127.0.0.1:4444",
        "proxyPort": "null",
        "password": "",
        "keepAlive": "null",
        "deviceAction": "null",
        "provider": "SELENIUM",
        "gridInstance": "null",
        "name": "local",
        "description": "",
        "userName": "",
        "proxyHost": "null",
        "gesture": "null"
    },
    "contextMap": "null",
    "device": {
        "capabilities": {"_testName": "TC01_ValidLogin"},
        "os": "Windows",
        "active": true,
        "deviceLock": "java.util.concurrent.Semaphore@7282847e[Permits = 1]",
        "deviceName": "null",
        "resolution": "null",
        "capList": [
            "org.xframium.device.DeviceCap@5544fed3",
            "org.xframium.device.DeviceCap@2f003ce2",
            "org.xframium.device.DeviceCap@49c7ec08"
        ],
        "driverType": "WEB",
        "tagNames": [
            "ChromeBrowser",
            "Desktop"
        ],
        "manufacturer": "Google",
        "cloud": "local",
        "environment": "Windows chrome",
        "phoneNumber": "null",
        "osVersion": "null",
        "browserVersion": "null",
        "availableDevices": "1",
        "browserName": "chrome",
        "model": "Chrome",
        "cachedString": "Google Chrome [Chrome]",
        "key": "Chrome"
    },
    "messageDetail": "null"
}};